import React, { useState } from 'react';
import Image from 'next/image';
import { ChevronDown, HelpCircle, MessageCircle } from 'lucide-react';

const faqs = [
    {
        question: "What is STOF?",
        answer:
            "STOF is the native token of the STONEFORM ecosystem. It is designed to provide holders with fractional exposure to tokenized real estate assets, participation rights within the platform, and access to revenue generated by underlying properties.",
    },
    {
        question: "Is STOF a regulated investment?",
        answer:
            "STONEFORM is structured to operate in compliance with applicable regulations related to tokenized real estate and digital securities. The STOF token is designed with a strong focus on transparency, legal compliance, and investor protection, as outlined in the whitepaper.",
    },
    {
        question: "How do STOF holders benefit from the ecosystem?",
        answer:
            "STOF holders may benefit from revenue distributions linked to real estate performance, participation in platform governance, and access to exclusive investment opportunities within the STONEFORM ecosystem, subject to applicable terms and conditions.",
    },
    {
        question: "Can STOF tokens be traded?",
        answer:
            "STOF tokens are intended to be tradable following public listing, subject to regulatory requirements and platform conditions. Liquidity mechanisms and secondary market access will be introduced progressively in alignment with the project roadmap.",
    },
    {
        question: "Is there a minimum investment amount?",
        answer:
            "Minimum investment requirements depend on the token sale phase. Early phases are structured to allow broad participation while maintaining compliance with applicable regulatory frameworks.",
    },
    {
        question: "What makes STONEFORM different?",
        answer:
            "STONEFORM bridges real-world real estate assets with blockchain technology, enabling fractional access to premium properties, transparent on-chain revenue distribution, and a long-term, asset-backed investment model.",
    },
];


const FAQ = () => {
    const [openIndex, setOpenIndex] = useState<number | null>(null);

    const toggleFAQ = (index: number) => {
        setOpenIndex(openIndex === index ? null : index);
    };

    return (
        <section className="relative w-full py-24 px-4 md:px-8 bg-stone-dark text-white flex flex-col justify-center items-center overflow-hidden" id="faq">
            {/* Background Image & Overlays */}
            <div
                className="absolute inset-0 z-0 bg-[url('/stoneform-faq-bg.png')] bg-cover bg-top bg-fixed opacity-30"
            >
                <div className="absolute inset-0 bg-gradient-to-b from-stone-dark via-stone-dark/80 to-stone-dark"></div>
            </div>

            <div className="absolute top-0 left-0 w-full h-32 bg-gradient-to-b from-stone-dark to-transparent pointer-events-none z-20"></div>
            <div className="absolute bottom-0 left-0 w-full h-32 bg-gradient-to-t from-stone-dark to-transparent pointer-events-none z-20"></div>

            <div className="relative z-10 max-w-4xl w-full">
                <div className="text-center mb-16">
                    <h2 className="text-4xl md:text-7xl font-bold mb-4 tracking-tight">
                        <span className="text-white drop-shadow-[0_0_15px_rgba(168,85,247,0.8)]">FAQ</span>
                    </h2>
                    <p className="text-lg text-gray-400 max-w-xl mx-auto font-light">
                        Everything you need to know about the STONEFORM ecosystem and investment process.
                    </p>
                </div>

                <div className="space-y-4">
                    {faqs.map((faq, index) => (
                        <div
                            key={index}
                            className={`glass-card rounded-2xl overflow-hidden transition-all duration-300 border ${openIndex === index ? 'bg-white/10 border-stone-cyan/30 shadow-[0_0_20px_rgba(0,198,255,0.1)]' : 'bg-white/5 border-white/5 hover:bg-white/10 hover:border-white/10'}`}
                        >
                            <button
                                onClick={() => toggleFAQ(index)}
                                className="w-full flex items-center justify-between p-6 text-left focus:outline-none group"
                            >
                                <div className="flex items-center gap-4">
                                    <div className={`w-8 h-8 rounded-full flex items-center justify-center transition-colors duration-300 ${openIndex === index ? 'bg-stone-cyan/20 text-stone-cyan' : 'bg-white/5 text-gray-400 group-hover:text-white'}`}>
                                        <HelpCircle className="w-5 h-5" />
                                    </div>
                                    <span className={`text-lg md:text-xl font-bold transition-colors duration-300 ${openIndex === index ? 'text-white' : 'text-gray-200 group-hover:text-white'}`}>
                                        {faq.question}
                                    </span>
                                </div>
                                <div className={`w-8 h-8 rounded-full flex items-center justify-center border border-white/10 transition-all duration-300 ${openIndex === index ? 'bg-stone-cyan text-stone-dark rotate-180' : 'bg-transparent text-gray-400 group-hover:bg-white/10 group-hover:text-white'}`}>
                                    <ChevronDown className="w-5 h-5" />
                                </div>
                            </button>

                            <div
                                className={`transition-all duration-500 ease-in-out overflow-hidden ${openIndex === index ? 'max-h-96 opacity-100' : 'max-h-0 opacity-0'}`}
                            >
                                <div className="p-6 pt-0 text-gray-300 font-light leading-relaxed border-t border-white/5 mx-6 mt-2">
                                    <p className="py-4">{faq.answer}</p>
                                </div>
                            </div>
                        </div>
                    ))}
                </div>

                <div className="mt-12 text-center">
                    <p className="text-gray-400 mb-6">Still have questions?</p>
                    <button className="px-8 py-3 bg-white/5 hover:bg-white/10 border border-white/10 rounded-full text-white font-medium transition-all duration-300 flex items-center gap-2 mx-auto hover:scale-105 group">
                        <MessageCircle className="w-4 h-4 text-stone-cyan group-hover:text-stone-purple transition-colors" />
                        Contact Support
                    </button>
                </div>
            </div>
        </section>
    );
};

export default FAQ;
